{ pkgs, lib, config, ... }:

{
  imports = [
    ./intel-generic.nix
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  environment.systemPackages = with pkgs; [
    beignet
    ocl-icd
    intel-ocl
    libva
  ];

  boot = {
    #extraModulePackages = with pkgs.linuxPackages_hardened; [ it87 ];
    extraModulePackages = with pkgs.linuxPackages_latest; [ it87 ];
    kernelModules = [
      "kvm-intel"
      "coretemp"
      "it87"
    ];
  };

  services.xserver.videoDrivers = [ "intel" ];

  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
  };

  hardware = {
    opengl = {
      enable = true;
      extraPackages = with pkgs; [
        vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
        intel-media-driver
        intel-ocl
      ];
      s3tcSupport = true;
    };

    # fancontrol = {
    #   enable = true;
    #   config = ''
    #     INTERVAL=10
    #     DEVPATH=hwmon0=devices/platform/coretemp.0 hwmon1=devices/platform/it87.2592
    #     DEVNAME=hwmon0=coretemp hwmon1=it8613
    #     FCTEMPS=hwmon1/pwm3=hwmon0/temp1_input
    #     FCFANS= hwmon1/pwm3=hwmon1/fan3_input
    #     MINTEMP=hwmon1/pwm3=20
    #     MAXTEMP=hwmon1/pwm3=60
    #     MINSTART=hwmon1/pwm3=52
    #     MINSTOP=hwmon1/pwm3=12
    #     
    #     # Configuration file generated by pwmconfig
    #     INTERVAL=10
    #     DEVPATH=hwmon3=devices/virtual/thermal/thermal_zone2 hwmon4=devices/platform/f71882fg.656
    #     DEVNAME=hwmon3=soc_dts1 hwmon4=f71869a
    #     FCTEMPS=hwmon4/device/pwm1=hwmon3/temp1_input
    #     FCFANS= hwmon4/device/pwm1=hwmon4/device/fan1_input
    #     MINTEMP=hwmon4/device/pwm1=35
    #     MAXTEMP=hwmon4/device/pwm1=65
    #     MINSTART=hwmon4/device/pwm1=150
    #     MINSTOP=hwmon4/device/pwm1=0
    #   '';
    # };
  };
}
